    ##
    # Spring Security - OAuth2 Resource Server
    ##
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri:  http://localhost:18080/realms/my-app-realm
                    jwk-set-uri: http://localhost:18080/realms/my-app-realm/protocol/openid-connect/certs
