name: java-spring-security-oauth2-resourceserver-plugin
description: Plugin to enable and configure Spring Security OAuth2 Resource Server in Java Spring Boot applications
display-name: java-spring-security-oauth2-resourceserver-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
  - maven
  - aplication.yaml
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app

computed-inputs:
  application_package_folder: "{{application_package|replace('.', '/')}}"

hooks:
  ##
  # Edit application.yaml
  ##
  - type: edit
    path: src/main/resources/application.yaml
    trigger: after-render    
    changes:
      - search:
          string: "spring:"
          insert-after:
            snippet: snippets/snippet-application.yaml
          when:
            not-exists: "resourceserver:"
  ##
  # Edit pom.xml
  ##
  - type: edit
    path: pom.xml
    trigger: after-render    
    changes:
      - search:
          string: "</dependencies>"
          insert-before:
            snippet: snippets/snippet-pom.xml
          when:
            not-exists-snippet: snippets/snippet-pom.xml
  ##
  # Create or edit docker-compose.yaml
  ##
  - type: render-templates
    trigger: after-render
    path: snippets/docker-keycloak
  ##
  # Create path directory samples
  ##
  - type: run-script
    trigger: after-render
    script: snippets/open-pom.py